"""Final Markdown document assembly."""

from __future__ import annotations

from pathlib import Path

from .models import FileRecord
from .tree import build_ascii_tree

LANG_BY_EXT = {
    ".py": "python", ".js": "javascript", ".ts": "typescript", ".tsx": "tsx",
    ".jsx": "jsx", ".go": "go", ".rs": "rust", ".java": "java", ".kt": "kotlin",
    ".c": "c", ".cpp": "cpp", ".h": "c", ".hpp": "cpp", ".rb": "ruby",
    ".php": "php", ".sh": "bash", ".bash": "bash", ".md": "markdown",
    ".json": "json", ".yml": "yaml", ".yaml": "yaml", ".toml": "toml",
    ".html": "html", ".css": "css", ".sql": "sql",
}


def lang_for(rel_path: str) -> str:
    return LANG_BY_EXT.get(Path(rel_path).suffix.lower(), "")


def render_markdown(
    root_name: str,
    included: list[FileRecord],
    dropped_for_budget: list[FileRecord],
    skipped: list[FileRecord],
    budget: int,
    elapsed: float,
    token_backend: str = "heuristic",
) -> str:
    total_tokens = sum(r.tokens for r in included)
    out: list[str] = []

    out.append(f"# Context Pack: `{root_name}`")
    out.append("")
    out.append(
        f"_Generated by ctx-pack · {len(included)} file(s) · "
        f"{total_tokens:,} tokens ({token_backend}) · {elapsed:.2f}s_"
    )
    out.append("")

    if budget > 0:
        out.append(f"**Token budget:** {total_tokens:,} / {budget:,} used")
        out.append("")

    out.append("## Directory Structure")
    out.append("")
    out.append("```")
    out.append(build_ascii_tree([r.rel_path for r in included]))
    out.append("```")
    out.append("")

    if dropped_for_budget:
        out.append("## ⚠️ Omitted Due to Token Budget")
        out.append("")
        out.append("| File | Tokens | Priority Tier |")
        out.append("|---|---|---|")
        for r in sorted(dropped_for_budget, key=lambda r: -r.tokens):
            out.append(f"| `{r.rel_path}` | {r.tokens:,} | {r.effective_priority} |")
        out.append("")

    if skipped:
        out.append("## ℹ️ Skipped Files")
        out.append("")
        out.append("| File | Reason |")
        out.append("|---|---|")
        for r in skipped:
            out.append(f"| `{r.rel_path}` | {r.skipped_reason} |")
        out.append("")

    out.append("## Files")
    out.append("")
    for r in included:
        lang = lang_for(r.rel_path)
        out.append(f"### `{r.rel_path}`")
        out.append("")
        out.append(f"```{lang}")
        out.append(r.content.rstrip("\n"))
        out.append("```")
        out.append("")

    return "\n".join(out)
